/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Edu Santos design tokens
        "surface": "#f9f9ff",
        "surface-dim": "#d3daea",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eefe",
        "surface-container-high": "#e2e8f8",
        "surface-container-highest": "#dce2f3",
        "surface-variant": "#dce2f3",
        "on-surface": "#151c27",
        "on-surface-variant": "#434751",
        "on-background": "#151c27",
        "outline": "#737782",
        "outline-variant": "#c3c6d3",
        "inverse-surface": "#2a313d",
        "inverse-on-surface": "#ebf1ff",
        "inverse-primary": "#afc6ff",
        "primary-brand": "#00357b",
        "on-primary": "#ffffff",
        "primary-container": "#1e4c9a",
        "on-primary-container": "#a6c0ff",
        "primary-fixed": "#d9e2ff",
        "primary-fixed-dim": "#afc6ff",
        "tertiary": "#11376d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2e4e85",
        "on-tertiary-container": "#a2c1ff",
        "tertiary-fixed": "#d7e2ff",
        "secondary-brand": "#735c00",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffcf1e",
        "on-secondary-container": "#705900",
        "secondary-fixed": "#ffe087",
        "secondary-fixed-dim": "#f0c100",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Montserrat", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.625rem",
        "sm": "calc(var(--radius) - 4px)",
        "md": "calc(var(--radius) - 2px)",
        "lg": "var(--radius)",
        "xl": "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 12px)",
      },
      spacing: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
}